{
 "title": "Customer Sentiment",
 "time": { "from": "2008-12-31T18:30:00.000Z", "to": "2013-12-31T18:30:00.000Z" },
 "panels": [
  { "title": "Amazon Brand Sentiment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"Canon\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'Canon' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    },
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"Sony\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'Sony' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    },
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"Logitech\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'Logitech' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    },
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"Belkin\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'Belkin' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    },
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"SanDisk\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'SanDisk' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    },
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"Tamron\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'Tamron' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    },
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"Sigma\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'Sigma' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    },
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"Pentax\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'Pentax' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    },
    {
     "rawSql": "SELECT to_date('0101' || \"Year\", 'DDMMYYYY') as \"Date\", \"SentimentRank\" as \"Fujifilm\"\nFROM \"BrandSentimentVsTime\"\nWHERE \"Brand\" = 'Fujifilm' AND \"Year\" >= 2000\nORDER BY to_date('0101' || \"Year\", 'DDMMYYYY') ASC"
    }
   ]
  },
  { "title": "Brands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "5 Most Popular Brands ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \"Brand\", ROUND(\"SentimentRank\") AS \"Sentiment Score\"\nFROM \"BrandSentiment\"\nORDER BY \"ReviewCount\" DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "5 Least Popular Brands ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \"Brand\", ROUND(\"SentimentRank\") AS \"Sentiment Score\"\nFROM \"BrandSentiment\"\nORDER BY \"ReviewCount\" ASC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "5 Most Loved Brands ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \"Brand\", ROUND(\"SentimentRank\") AS \"Sentiment Score\"\nFROM \"BrandSentiment\"\nORDER BY \"SentimentRank\" DESC, \"ReviewCount\" DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "5 Least Loved Brands ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT \"Brand\", ROUND(\"SentimentRank\") AS \"Sentiment Score\"\nFROM \"BrandSentiment\"\nORDER BY \"SentimentRank\" ASC, \"ReviewCount\" ASC\nLIMIT 5"
    }
   ]
  },
  { "title": "Products", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "5 Most Popular Products ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Name\", \"Brand\", \"SentimentRank\" AS \"Sentiment Score\"\nFROM \"ProductSentiment\"\nORDER BY \"ReviewCount\" DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "5 Most Loved Products ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Name\", \"Brand\", \"SentimentRank\" AS \"Sentiment Score\"\nFROM \"ProductSentiment\"\nORDER BY \"SentimentRank\" DESC, \"ReviewCount\" DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "5 Least Popular Brands ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Brand\", \"SentimentRank\" AS \"Sentiment Score\"\nFROM \"BrandSentiment\"\nORDER BY \"ReviewCount\" ASC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "5 Least Loved Brands ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Brand\", \"SentimentRank\" AS \"Sentiment Score\"\nFROM \"BrandSentiment\"\nORDER BY \"SentimentRank\" ASC, \"ReviewCount\" ASC\nLIMIT 5"
    }
   ]
  },
  { "title": "Categories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "5 Best Product Categories ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Category\", ROUND(\"SentimentRank\") AS \"Sentiment Score\"\nFROM \"ItemCategorySentiment\"\nORDER BY \"SentimentRank\" DESC, \"ReviewCount\" DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "5 Worst Product Categories ??",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"Category\", ROUND(\"SentimentRank\") AS \"Sentiment Score\"\nFROM \"ItemCategorySentiment\"\nORDER BY \"SentimentRank\" ASC, \"ReviewCount\" ASC\nLIMIT 5"
    }
   ]
  }
 ]
}