{
 "title": "Demand",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Top Brands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Amazon Devices",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'Amazon Devices'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Canon Demand",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Brand\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"BrandDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Brand\" = 'Canon'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Sony Demand",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Brand\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"BrandDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Brand\" = 'Sony'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Logitech Demand",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Brand\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"BrandDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Brand\" = 'Logitech'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Belkin Demand",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Brand\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"BrandDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Brand\" = 'Belkin'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  { "title": "Small Electronics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Best Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'All Electronics'\r\n\tORDER BY \"Demand\" DESC\r\n\tLIMIT 1) T"
    }
   ]
  },
  {
   "title": "Small Electronics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'All Electronics'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Worst Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'All Electronics'\r\n\tORDER BY \"Demand\" ASC\r\n\tLIMIT 1) T"
    }
   ]
  },
  { "title": "Home Audio & Theater", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Best Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Home Audio & Theater'\r\n\tORDER BY \"Demand\" DESC\r\n\tLIMIT 1) T"
    }
   ]
  },
  {
   "title": "Home Audio & Theater",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'Home Audio & Theater'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Worst Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Home Audio & Theater'\r\n\tORDER BY \"Demand\" ASC\r\n\tLIMIT 1) T"
    }
   ]
  },
  { "title": "Camera & Photo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Best Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Camera & Photo'\r\n\tORDER BY \"Demand\" DESC\r\n\tLIMIT 1) T"
    }
   ]
  },
  {
   "title": "Camera & Photo",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'Camera & Photo'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Worst Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Camera & Photo'\r\n\tORDER BY \"Demand\" ASC\r\n\tLIMIT 1) T"
    }
   ]
  },
  { "title": "Cell Phones & Accessories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Best Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Cell Phones & Accessories'\r\n\tORDER BY \"Demand\" DESC\r\n\tLIMIT 1) T"
    }
   ]
  },
  {
   "title": "Cell Phones & Accessories",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'Cell Phones & Accessories'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Worst Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Cell Phones & Accessories'\r\n\tORDER BY \"Demand\" ASC\r\n\tLIMIT 1) T"
    }
   ]
  },
  { "title": "Computers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Best Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Computers'\r\n\tORDER BY \"Demand\" DESC\r\n\tLIMIT 1) T"
    }
   ]
  },
  {
   "title": "Computers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'Computers'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Worst Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Computers'\r\n\tORDER BY \"Demand\" ASC\r\n\tLIMIT 1) T"
    }
   ]
  },
  { "title": "Car Electronics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Best Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Car Electronics'\r\n\tORDER BY \"Demand\" DESC\r\n\tLIMIT 1) T"
    }
   ]
  },
  {
   "title": "Car Electronics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'Car Electronics'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Worst Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Car Electronics'\r\n\tORDER BY \"Demand\" ASC\r\n\tLIMIT 1) T"
    }
   ]
  },
  { "title": "Health & Personal Care", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Best Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Health & Personal Care'\r\n\tORDER BY \"Demand\" DESC\r\n\tLIMIT 1) T"
    }
   ]
  },
  {
   "title": "Health & Personal Care",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'Health & Personal Care'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Worst Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Health & Personal Care'\r\n\tORDER BY \"Demand\" ASC\r\n\tLIMIT 1) T"
    }
   ]
  },
  { "title": "Industrial & Scientific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Best Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Industrial & Scientific'\r\n\tORDER BY \"Demand\" DESC\r\n\tLIMIT 1) T"
    }
   ]
  },
  {
   "title": "Industrial & Scientific",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\" ,\"August\" ,\"September\" ,\"October\" ,\"November\" ,\"December\" \r\nFROM CROSSTAB(\r\n\t$$\r\n\t\tSELECT CD.\"Category\" AS \"rowid\", M.\"Month\" AS \"category\", COALESCE(CD.\"Demand\", 0) AS \"value\"\r\n\t\tFROM (SELECT GENERATE_SERIES AS \"Month\"  FROM GENERATE_SERIES(1,12)) M\r\n\t\tLEFT JOIN \"CategoryDemand\" CD ON CD.\"Month\" = M.\"Month\" AND CD.\"Category\" = 'Industrial & Scientific'\r\n\t\tORDER BY M.\"Month\"\r\n\t$$,\r\n\t$$ \r\n\t\tSELECT * FROM GENERATE_SERIES(1, 12)\r\n\t$$) AS \r\n\tFINAL_RESULT(\r\n\t\t\"Category\" TEXT, \"January\" NUMERIC, \"February\" NUMERIC, \"March\" NUMERIC, \"April\" NUMERIC, \"May\" NUMERIC, \"June\" NUMERIC,\r\n\t\t\"July\" NUMERIC, \"August\" NUMERIC, \"September\" NUMERIC, \"October\" NUMERIC, \"November\" NUMERIC, \"December\" NUMERIC)"
    }
   ]
  },
  {
   "title": "Worst Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TO_CHAR(TO_TIMESTAMP(\"Date\", 'YYYY-MM-DD'), 'Month') AS \"Month\", \"Demand\"\r\nFROM (\r\n\tSELECT CONCAT('2020-', \"Month\", '-01') AS \"Date\", \"Demand\"\r\n\tFROM \"CategoryDemand\"\r\n\tWHERE \"Category\" = 'Industrial & Scientific'\r\n\tORDER BY \"Demand\" ASC\r\n\tLIMIT 1) T"
    }
   ]
  }
 ]
}